// <auto-generated />
using System;
using KupeServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KupeServer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930164133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KupeServer.Api.Features.Auth.Entities.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_provider_provider_user_id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_user_id_provider");

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("double precision")
                        .HasColumnName("area_km2");

                    b.Property<string>("Capital")
                        .HasColumnType("text")
                        .HasColumnName("capital");

                    b.Property<string>("Continent")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("continent")
                        .IsFixedLength();

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("CurrencyName")
                        .HasColumnType("text")
                        .HasColumnName("currency_name");

                    b.Property<int>("GeonameId")
                        .HasColumnType("integer")
                        .HasColumnName("geoname_id");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso2")
                        .IsFixedLength();

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("iso3")
                        .IsFixedLength();

                    b.Property<string>("Languages")
                        .HasColumnType("text")
                        .HasColumnName("languages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhonePrefix")
                        .HasColumnType("text")
                        .HasColumnName("phone_prefix");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("GeonameId")
                        .IsUnique()
                        .HasDatabaseName("ix_country_geoname_id");

                    b.HasIndex("Iso2")
                        .IsUnique()
                        .HasDatabaseName("ix_country_iso2");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Admin1Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("admin1_code");

                    b.Property<string>("AsciiName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ascii_name");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<int?>("Elevation")
                        .HasColumnType("integer")
                        .HasColumnName("elevation");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("feature_code");

                    b.Property<int>("GeonameId")
                        .HasColumnType("integer")
                        .HasColumnName("geoname_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Population")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("population");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.HasKey("Id")
                        .HasName("pk_place");

                    b.HasIndex("Admin1Code")
                        .HasDatabaseName("ix_place_admin1_code");

                    b.HasIndex("AsciiName")
                        .HasDatabaseName("ix_place_ascii_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AsciiName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("AsciiName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("GeonameId")
                        .IsUnique()
                        .HasDatabaseName("ix_place_geoname_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_place_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CountryId", "Population")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_place_country_id_population");

                    b.HasIndex("Lat", "Lon")
                        .HasDatabaseName("ix_place_lat_lon");

                    b.ToTable("place", (string)null);
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.PlaceName", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred");

                    b.HasKey("PlaceId", "Language", "Name")
                        .HasName("pk_place_name");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_place_name_language");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_place_name_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("place_name", (string)null);
                });

            modelBuilder.Entity("KupeServer.Api.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KupeServer.Api.Features.Auth.Entities.ExternalIdentity", b =>
                {
                    b.HasOne("KupeServer.Api.Features.Users.Entities.User", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.Place", b =>
                {
                    b.HasOne("KupeServer.Api.Features.Countries.Entities.Country", "Country")
                        .WithMany("Places")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_place_country_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.PlaceName", b =>
                {
                    b.HasOne("KupeServer.Api.Features.Countries.Entities.Place", "Place")
                        .WithMany("Names")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_name_place_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.Country", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("KupeServer.Api.Features.Countries.Entities.Place", b =>
                {
                    b.Navigation("Names");
                });

            modelBuilder.Entity("KupeServer.Api.Features.Users.Entities.User", b =>
                {
                    b.Navigation("ExternalIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
